# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: node:latest
stages:
- test
- build
cache:
  paths:
  - node_modules/
  - ".yarn"
  - build
  - tsconfig.tsbuildinfo
include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
lint:
  stage: test
  allow_failure: true
  script:
  - yarn --frozen-lockfile
  - yarn lint --format gitlab
  artifacts:
    paths:
    - gl-codequality.json
    reports:
      codequality: gl-codequality.json
audit:
  stage: test
  script:
  - npx gitlab-ci-yarn-audit-parser
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
test:
  stage: build
  script:
  - yarn
sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, gosec, kubesec, phpcs-security-audit,
      pmd-apex, security-code-scan, sobelow, spotbugs
  stage: test
