# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: node:latest
stages:
- test
- build
cache:
  paths:
  - node_modules/
  - ".yarn"
  - build
  - tsconfig.tsbuildinfo
include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
lint:
  stage: test
  allow_failure: true
  script:
  - yarn --frozen-lockfile
  - yarn lint --format gitlab
  artifacts:
    paths:
    - gl-codequality.json
    reports:
      codequality: gl-codequality.json

audit:
  stage: test
  script:
    - npx gitlab-ci-yarn-audit-parser
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json

sast:
  stage: test
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, gosec, kubesec, phpcs-security-audit,
      pmd-apex, security-code-scan, sobelow, spotbugs

test-node-10:
  stage: build
  image: node:10
  needs: [ lint ]
  before_script:
    - yarn
    - yarn global add pg
    - cp $CI_ORM_CONFIG ormconfig.json
  script:
    - yarn test:coverage
  artifacts:
    reports:
      junit:
        - test-results.xml
      cobertura:
        - coverage/cobertura-coverage.xml

test-node-12:
  stage: build
  image: node:12
  needs: [ lint ]
  before_script:
    - yarn
    - yarn global add pg
    - cp $CI_ORM_CONFIG ormconfig.json
  script:
    - yarn test:coverage
  artifacts:
    reports:
      junit:
        - test-results.xml
      cobertura:
        - coverage/cobertura-coverage.xml

test-node-13:
  stage: build
  image: node:13
  needs: [ lint ]
  before_script:
    - yarn
    - yarn global add pg
    - cp $CI_ORM_CONFIG ormconfig.json
  script:
    - yarn test:coverage
  artifacts:
    reports:
      junit:
        - test-results.xml
      cobertura:
        - coverage/cobertura-coverage.xml

test-node-14:
  stage: build
  image: node:14
  needs: [ lint ]
  before_script:
    - yarn
    - yarn global add pg
    - cp $CI_ORM_CONFIG ormconfig.json
  script:
    - yarn test:coverage
  artifacts:
    reports:
      junit:
        - test-results.xml
      cobertura:
        - coverage/cobertura-coverage.xml

test-node-15:
  stage: build
  image: node:15
  needs: [ lint ]
  before_script:
    - yarn
    - yarn global add pg
    - cp $CI_ORM_CONFIG ormconfig.json
  script:
    - yarn test:coverage
  artifacts:
    reports:
      junit:
        - test-results.xml
      cobertura:
        - coverage/cobertura-coverage.xml
